// GENERATED by build.py --coupon. A wall-thickness plate with one slot,
// printed standing up like a wall so the pointed top prints as it would in a box.
include <../scad/enclosure.scad>
WALL = 2.4;
rotate([90, 0, 0]) linear_extrude(WALL) difference() {
  translate([-13.8, 0]) square([27.6, 30.0]);
  translate([0, 10.1]) pointed2d(15.6, 10.2, 1.0, 7.8);
}
