// GENERATED by build.py --coupon. A wall-thickness plate with one slot,
// printed standing up like a wall so the pointed top prints as it would in a box.
include <../scad/enclosure.scad>
WALL = 2.4;
rotate([90, 0, 0]) linear_extrude(WALL) difference() {
  translate([-14.25, 0]) square([28.5, 29.35]);
  translate([0, 9.55]) pointed2d(16.5, 9.1, 1.0, 8.25);
}
