"""build.py entry point: YAML -> layout -> checks -> SCAD -> STL / PNG / BOM."""
from __future__ import annotations

import argparse
import sys

from .config import ConfigError, enclosure_dir, list_enclosures, load_enclosure
from .emit import stl_name, write_bom, write_scad
from .layout import build_model
from .render import render_png, render_stl
from .validate import validate

# rot x, y, z for --camera=tx,ty,tz,rx,ry,rz,dist (dist is replaced by --viewall)
VIEWS = {
    "assembly": ("assembly", "0,0,0,60,0,325,500"),     # from the front-left
    "assembly_back": ("assembly", "0,0,0,60,0,145,500"),  # from the back-right
    "interior": ("interior", "0,0,0,40,0,325,500"),
    "interior_top": ("interior", "0,0,0,0,0,0,500"),
    "base": ("base", "0,0,0,50,0,325,500"),             # empty box, no lid, from the front-left
    "base_back": ("base", "0,0,0,50,0,145,500"),        # empty box, no lid, from the back-right
    "base_top": ("base", "0,0,0,0,0,0,500"),            # empty box straight down: every floor feature visible
    "lid": ("lid", "0,0,0,40,0,325,500"),               # as printed, lip up
}


def build(name: str, check_only: bool, previews: bool) -> bool:
    print(f"== {name}")
    try:
        cfg = load_enclosure(name)
    except ConfigError as e:
        print(f"  ERROR {e}")
        return False
    m = build_model(cfg)
    if not m.errors:
        validate(m)
    for w in m.checks:
        print(f"  check: {w}")
    for w in m.warnings:
        print(f"  warning: {w}")
    for e in m.errors:
        print(f"  ERROR {e}")
    if m.errors:
        return False

    out = enclosure_dir(name)
    wrappers = write_scad(m, out / "build")
    write_bom(m, out / "BOM.md")
    print(f"  wrote {out.name}/build/*.scad and {out.name}/BOM.md")
    if check_only:
        return True
    from .validate import plate_layout
    parts = ["base", "lid"] + (["plate"] if plate_layout(m) else [])
    stale = out / "stl" / stl_name(name, "plate")
    if "plate" not in parts and stale.exists():
        stale.unlink()   # an old plate file would no longer match the parts
    for part in parts:
        render_stl(wrappers[part], out / "stl" / stl_name(name, part))
        print(f"  wrote {out.name}/stl/{stl_name(name, part)}")
    if previews:
        for view, (part, camera) in VIEWS.items():
            render_png(wrappers[part], out / "preview" / f"{view}.png", camera)
        print(f"  wrote {out.name}/preview/*.png")
    return True


def coupon(part: str) -> bool:
    """Print-in-minutes test plate with one pass-through slot, cut exactly as in
    a wall (same pointed top), so a connector can be test-fitted before a whole
    base is printed."""
    import subprocess
    from .config import ROOT, load_component
    from .render import find_openscad
    try:
        spec = load_component("passthrough", part)
    except ConfigError as e:
        print(f"  ERROR {e}")
        return False
    s = spec["slot"]
    w, h, r = s["w"], s["h"], s.get("r", 0)
    out = ROOT / "test-prints" / f"{part}-coupon.stl"
    out.parent.mkdir(exist_ok=True)
    scad = out.with_suffix(".scad")
    lib = "../scad/enclosure.scad"
    scad.write_text(
        "// GENERATED by build.py --coupon. A wall-thickness plate with one slot,\n"
        "// printed standing up like a wall so the pointed top prints as it would in a box.\n"
        f"include <{lib}>\nWALL = 2.4;\n"
        f"rotate([90, 0, 0]) linear_extrude(WALL) difference() {{\n"
        f"  translate([-{w / 2 + 6}, 0]) square([{w + 12}, {h + w / 2 + 12}]);\n"
        f"  translate([0, {h / 2 + 5}]) pointed2d({w}, {h}, {r}, {w / 2});\n}}\n")
    subprocess.run([find_openscad(), "--backend=manifold", "-o", str(out), str(scad)], check=True,
                   capture_output=True)
    print(f"  wrote test-prints/{out.name}")
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build enclosure STLs from enclosures/<name>/enclosure.yaml")
    ap.add_argument("names", nargs="*", help="enclosure names (default: all)")
    ap.add_argument("--check", action="store_true", help="validate and write SCAD/BOM only, no STL")
    ap.add_argument("--no-preview", action="store_true", help="skip PNG previews")
    ap.add_argument("--coupon", metavar="PART", help="only write a test-fit plate for a passthrough part")
    a = ap.parse_args(argv)
    if a.coupon:
        return 0 if coupon(a.coupon) else 1
    names = a.names or list_enclosures()
    if not names:
        print("no enclosures found under enclosures/")
        return 1
    ok = all([build(n, a.check, not a.no_preview) for n in names])
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
