"""Write the generated OpenSCAD inputs and the BOM for one enclosure."""
from __future__ import annotations

import os
from collections import defaultdict
from pathlib import Path

from .config import SCAD_LIB
from .layout import Model
from .validate import footprints, plate_layout

def stl_name(name: str, part: str) -> str:
    """Printed-part file name; carries the enclosure name so files stay
    identifiable once copied to a slicer or another folder (owner's convention)."""
    return f"{name}-enclosure-{part}.stl"


PARTS = {
    "base": "part_base_print();",
    "lid": "part_lid_print();",
    "assembly": "part_assembly();",
    "plate": "part_plate();",
    "interior": "part_interior();",
}


def scad_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return f"{round(float(v), 4):g}"
    if isinstance(v, str):
        return '"' + v.replace('"', '\\"') + '"'
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(scad_value(x) for x in v) + "]"
    raise TypeError(f"cannot write {v!r} to OpenSCAD")


def write_scad(m: Model, build_dir: Path) -> dict[str, Path]:
    build_dir.mkdir(parents=True, exist_ok=True)
    lines = [f"// GENERATED by enclosure_builder from enclosures/{m.cfg['name']}/enclosure.yaml",
             "// Do not edit: change the YAML and rebuild.", ""]
    for k, v in m.scalars.items():
        lines.append(f"{k} = {scad_value(v)};")
    pl = plate_layout(m)
    lines.append(f"PLATE_LID = {scad_value([pl[0], pl[1]] if pl else [0, 0])};")
    lines.append("")
    for k, items in m.prims.items():
        if not items:
            lines.append(f"{k} = [];")
            continue
        lines.append(f"{k} = [")
        lines += [f"  {scad_value(it)}," for it in items]
        lines.append("];")
    (build_dir / "params.scad").write_text("\n".join(lines) + "\n")

    lib = os.path.relpath(SCAD_LIB, build_dir)
    out = {}
    for part, call in PARTS.items():
        p = build_dir / f"{part}.scad"
        p.write_text(f"// GENERATED — open in OpenSCAD to inspect. Rebuild with build.py.\n"
                     f"include <{lib}>\ninclude <params.scad>\n{call}\n")
        out[part] = p
    return out


def drilling_guide(m: Model) -> list:
    """Where to drill the mounting surface under floor wire exits, measured
    from the first mounting hole, so wires can pass through the board the
    enclosure is screwed to."""
    holes, wall = getattr(m, "floor_drills", []), m.cfg["box"]["wall"]
    if not holes:
        return []
    if m.prims["TABS"]:
        t = m.prims["TABS"][0]
        reach = wall + t[2] * 0.55       # hole centre out from the interior face (see scad tab())
        ref = {"front": (t[1], -reach), "back": (t[1], m.W + reach),
               "left": (-reach, t[1]), "right": (m.L + reach, t[1])}[t[0]]
        ref_name = f"the {t[0]}-wall mounting tab hole"
    elif m.prims["FLOOR_MOUNTS"]:
        ref, ref_name = tuple(m.prims["FLOOR_MOUNTS"][0][:2]), "the first floor mounting hole"
    else:
        return []
    out = ["## Drilling the mounting surface", "",
           f"Floor wire exits pass through the board below. Hole centres, measured from {ref_name} "
           "(x to the right, y toward the back, looking down on the enclosure):", ""]
    for x, y, w, h, drill in holes:
        pos = f"- x {x - ref[0]:+.1f} mm, y {y - ref[1]:+.1f} mm: "
        if drill:
            out.append(pos + f"drill {drill:g} mm straight through the {w:g} mm hole, with the enclosure "
                       f"screwed down and empty (the bit clears the plastic by {(w - drill) / 2:g} mm all round)")
        else:
            d = (w ** 2 + h ** 2) ** 0.5
            out.append(pos + f"drill ≥ {d + 1.5:.0f} mm (clears the {w:g} × {h:g} slot and the connector through it)")
    return out + [""]


def write_bom(m: Model, path: Path) -> None:
    hardware = defaultdict(lambda: [0, []])
    for qty, item, purpose in m.bom:
        hardware[item][0] += qty
        hardware[item][1].append(f"{qty} {purpose}")
    fp = footprints(m)
    c = m.cfg
    lines = [
        f"# {c['name']} — build sheet",
        "",
        "GENERATED by `build.py` from `enclosure.yaml`. Do not edit; rebuild instead.",
        "",
        "| Base, no lid | Base with parts, no lid | Closed |",
        "|---|---|---|",
        "| ![base](preview/base.png) | ![parts](preview/interior.png) | ![closed](preview/assembly.png) |",
        "",
        "Parts are drawn as blocks: grey PSU, green perfboards, black connector bodies; light blue is "
        "board clearance, orange is wiring space.",
        "",
        "## Printed parts",
        "",
        "| File | Print orientation | Size (x × y × z mm) | Supports |",
        "|---|---|---|---|",
        f"| `stl/{stl_name(c['name'], 'base')}` | floor on the bed | {fp['base'][0]:.1f} × {fp['base'][1]:.1f} × {fp['base'][2]:.1f} | "
        + ("; ".join(m.support_notes) if m.support_notes else "none") + " |",
        f"| `stl/{stl_name(c['name'], 'lid')}` | top face on the bed, lip up | {fp['lid'][0]:.1f} × {fp['lid'][1]:.1f} × {fp['lid'][2]:.1f} | none |",
        "",
        "Bed: " + "; ".join(f"{part} leaves {left:.1f} mm spare on its tightest axis"
                            for part, sx, sy, left in getattr(m, "bed_report", []) if left is not None)
        + f" ({c['printer']['bed'][0]} x {c['printer']['bed'][1]} bed, {c['printer'].get('bed_margin', 0)} mm margin kept).",
        "",
        (f"Both parts fit on one plate: `stl/{stl_name(c['name'], 'plate')}` "
         f"({plate_layout(m)[2]:.1f} × {plate_layout(m)[3]:.1f} mm), already arranged."
         if plate_layout(m) else "Base and lid do not fit on one plate together; print them separately."),
        "",
        "The lid needs no hardware: drop it in shifted toward the left wall, slide it right until the "
        "tab clicks. To open, lift the tab at the left edge and slide the lid left.",
        "",
        "Print in PETG or ASA, not PLA: the PSU case runs warm at full load and PLA creeps under the bolted PSU pads.",
        "",
        "## Hardware",
        "",
        "| Qty | Item | Used for |",
        "|---|---|---|",
    ]
    for item, (qty, uses) in sorted(hardware.items()):
        lines.append(f"| {qty} | {item} | {'; '.join(uses)} |")
    lines += ["", "## Interior", "",
              f"{m.L} × {m.W} × {m.H} mm (L × W × H), wall {c['box']['wall']} mm, floor {c['box']['floor']} mm.", ""]
    lines += drilling_guide(m)
    if m.checks:
        lines += ["## Check before printing", "",
                  "Taken from datasheets, not measured on your parts:", ""] + [f"- {w}" for w in m.checks] + [""]
    if m.warnings:
        lines += ["## Warnings", ""] + [f"- {w}" for w in m.warnings] + [""]
    path.write_text("\n".join(lines))
